# Generated by Django 4.2 on 2024-12-18 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المشروع')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز المشروع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المشروع')),
                ('client_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف العميل')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد العميل')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('expected_end_date', models.DateField(verbose_name='تاريخ الانتهاء المتوقع')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء الفعلي')),
                ('status', models.CharField(choices=[('planning', 'تخطيط'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('on_hold', 'متوقف'), ('cancelled', 'ملغي')], default='planning', max_length=20, verbose_name='حالة المشروع')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الميزانية الكلية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('accountant', models.ForeignKey(limit_choices_to={'role': 'accountant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='المحاسب المسؤول')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
    ]
