version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=construction_accounting
      - DB_USER=root
      - DB_PASSWORD=5294507**
      - DB_HOST=db
      - DB_PORT=3306

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=construction_accounting
      - MYSQL_ROOT_PASSWORD=5294507**
    ports:
      - "3306:3306"

volumes:
  mysql_data:
