version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

  web:
    build: .
    command: gunicorn construction_accounting.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DB_NAME=construction_accounting
      - DB_USER=production_user
      - DB_PASSWORD=strong_password_here
      - DB_HOST=db
      - DB_PORT=3306
      - DJANGO_SETTINGS_MODULE=construction_accounting.settings
      - DEBUG=0
      - ALLOWED_HOSTS=your-domain.com,www.your-domain.com

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=construction_accounting
      - MYSQL_USER=production_user
      - MYSQL_PASSWORD=strong_password_here
      - MYSQL_ROOT_PASSWORD=very_strong_root_password
    restart: always

volumes:
  mysql_data:
