# Generated by Django 4.2 on 2024-12-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '__first__'),
        ('invoices', '0002_alter_invoiceitem_price_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='inventory.item', verbose_name='الصنف'),
        ),
    ]
