# Generated by Django 4.2 on 2024-12-20 13:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
    ]
