# Generated by Django 4.2 on 2024-12-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_status',
            field=models.CharField(choices=[('taxable', 'خاضع للضريبة'), ('exempt', 'معفى من الضريبة'), ('zero_rated', 'نسبة صفرية')], default='taxable', max_length=20, verbose_name='حالة الضريبة'),
        ),
    ]
