# Generated by Django 4.2 on 2024-12-18 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الحساب')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20, verbose_name='نوع الحساب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.accounttree', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'شجرة الحسابات',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('type', models.CharField(choices=[('expense', 'مصروف'), ('revenue', 'إيراد'), ('journal', 'قيد يومية')], max_length=20, verbose_name='نوع المعاملة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('reference_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'معاملة مالية',
                'verbose_name_plural': 'المعاملات المالية',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='دائن')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='الوصف')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.accounttree', verbose_name='الحساب')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.transaction', verbose_name='المعاملة')),
            ],
            options={
                'verbose_name': 'بند معاملة',
                'verbose_name_plural': 'بنود المعاملات',
            },
        ),
    ]
