# Generated by Django 4.2 on 2024-12-19 17:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الصنف')),
                ('unit', models.CharField(max_length=50, verbose_name='وحدة القياس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='سعر الوحدة')),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الرصيد الحالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'وارد'), ('out', 'منصرف')], max_length=3, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('reference_type', models.CharField(max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.IntegerField(verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_movements', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'حركة مخزنية',
                'verbose_name_plural': 'حركات المخزن',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
