# Generated by Django 4.2 on 2024-12-20 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'قالب تقرير', 'verbose_name_plural': 'قوالب التقارير'},
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
