# Generated by Django 4.2 on 2024-12-20 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reporttemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='من تاريخ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='إلى تاريخ'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التحديث'),
        ),
    ]
