# Generated by Django 4.2 on 2024-12-20 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_date_from_alter_report_date_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_from',
            field=models.DateField(default=datetime.date.today, verbose_name='من تاريخ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_to',
            field=models.DateField(default=datetime.date.today, verbose_name='إلى تاريخ'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ التحديث'),
        ),
    ]
