# Generated by Django 4.2 on 2024-12-20 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_created_at_alter_report_date_from_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='notes',
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_from',
            field=models.DateField(verbose_name='من تاريخ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_to',
            field=models.DateField(verbose_name='إلى تاريخ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('inventory', 'تقرير المخزون'), ('invoices', 'تقرير الفواتير'), ('suppliers', 'تقرير الموردين'), ('projects', 'تقرير المشاريع'), ('finance', 'تقرير المالية')], max_length=20, verbose_name='نوع التقرير'),
        ),
    ]
